// <auto-generated />
namespace Dispatcher.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserRelationToUserName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRelationToUserName));
        
        string IMigrationMetadata.Id
        {
            get { return "201602021922229_UserRelation-ToUserName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
